### ISSUE TITLE
Audiowalls

### ISSUE THREAD

**Issue by jamesdeane** [radiowarwick/digiplay#1]
## Required Functionality:
- Browse a list of audiowalls available to use/edit
- Select an audiowall set to use as your personal set
- Create new audiowall sets
- Create and delete audiowalls within a set
- Upload and browse for files, and search for music, and add these to an audiowall
- Rearrange audiowall items
- Save audiowall changes
## Completed Functionality as of 06/01/12:
- Music Search, adding to an audiowall
- Basic drag and drop rearranging

**Comment by djjavo** [comment]
## Completed Functionality as of 09/11/17:

- Browse a list of audiowalls available to use/edit
- Select an audiowall set to use as your personal set
- Create new audiowall sets
- Create and delete audiowalls within a set
- Upload and browse for files, and search for music, and add these to an audiowall
- Rearrange audiowall items
- Save audiowall changes
