### ISSUE TITLE
Updating Glyphicons to FontAwesome

### ISSUE THREAD

**Issue by ConnorPowell** [radiowarwick/digiplay#22]
Updating icons on the website from old [Glyphicons](http://glyphicons.com/) to the newer [FontAwesome](https://fontawesome.com/) library.

**Comment by djjavo** [comment]
Only comment I have is that I've noticed a delay on the icons loading after the page does - can we remove the defer so this does not happen?

**Comment by ConnorPowell** [comment]
Sure, doesn't seem to cause any issues doing so

**Comment by ConnorPowell** [comment]
Feature complete and live. Closing issue.
