### ISSUE TITLE
Sustainer Administration

### ISSUE THREAD

**Issue by djjavo** [radiowarwick/digiplay#24]
## Required Functionality:
- Have a key for the different playlists on `schedule.php`
    - Would be good if the playlist colours could automatically pick a useful colour
- Sustainer playlists should be editable by users with `Sustainer Admin`
   - Can pick a colour for schedule on creation
   - Warning `alert-warning` should be added to sustainer playlists that have below 40 tracks (or 2 hours in length)
- Fix schedule modal so it says time in helper text (currently `Select the playlist to be scheduled for .`).
- Advert manager should list only enabled adverts
    - Potentially have a search box like prerecords to add more adverts to the sustainer
    - Links on advert manager sidebar do not work
- Disable manual scheduling
    - Maybe have option panel in admin tools re-enable if needed

**Comment by ConnorPowell** [comment]
Just to clarify, what do you mean by
> Disable manual scheduling

I assume you mean so that you can't change the type of playlist for each hour?

Also what do you think of adding a simple cron script that resets the previous days scheduled prerecs? So at midnight Tuesday night all the prerecords are unscheduled from Tuesday.

**Comment by djjavo** [comment]
By disable manual scheduling I mean turning off the raw audio ID input. I think the cron job is a good idea, maybe do it weekly instead of daily though (10pm on a Sunday or something)?

**Comment by ConnorPowell** [comment]
Right, I see what you mean now, instead of having it a switch on the admin panel we could just make it so only users with admin permissions can see the tool on the page?

**Comment by djjavo** [comment]
Yeah, I'm happy for that to be the case for the manual input, similarly with the reset buttons. Maybe liaise with the PC to see what they would find helpful? It could also be configurable for admins to add more flexibility.

**Comment by ConnorPowell** [comment]
For auto-unscheduling of prerecords we decided it'd be best to just leave it as it is but if it's found to be useful in the future I'll just add that feature then.

**Comment by djjavo** [comment]
Changes from https://github.com/radiowarwick/digiplay/commit/f5135f2c789aaa615a0b3fb467033f4ad0396710 look good, just to add to the warnings, we could ideally do with a warning if the playlist contains an explicit track (as sue shouldn't play these)

**Comment by ConnorPowell** [comment]
Sure. I'll change the playlist track list so that explicit tracks appear first in the list and are clearly highlighted as explicit

**Comment by djjavo** [comment]
Thanks!

**Comment by ConnorPowell** [comment]
Feature complete and done!
